import { MenuItem } from 'primeng/api';
import { Message } from 'primeng/components/common/api';

export class Reginfo {
    regInfoModel: any = {};
    activeIndex: number = 0;
    items: MenuItem[];
    genderTypes: any;
    religeonList: any;
    relationList: any;
    selectedRegion: string = "0";
    selectedArea: string = "0";
    divisionList: any;
    selectedDivision: string = "0";
    districtList: any;
    selectedDistrict: string = "0";
    thanaList: any;
    photoIDTypeList: any;
    bankBranchList: any;
    selectedTerritory: string = "0";
    selectedCluster: string = "0";
    clusterList: any;
    distCode: string;
    currentUserModel: any = {};
    entityId: string;
    isEditMode: boolean = false;
    DistributorCode: string = "";
    regDate: any = {};
    dateOfBirth: any = {};
    formValidation: any;
    isFinalValdidate: boolean;
    kycTypes: any;
    isNidVerified: boolean;
    isLoading: boolean = false;
    isRegPermit = false;
    msgs: Message[] = [];
    error: boolean = false;
    showDuplicateMsg: boolean = false;
    customeNumberInput: any;
    date = new Date();
    occupationList: any;
    alphabetsWithSpace: any;
    emailRegx: any;
    showRejectModal: boolean = false;
    disableButton: boolean = false;
    checkedAsPresent: boolean = false;
    isReject: boolean;
    selectedKycType: any;
    showCbsModal: any;
    isFirstIndexShow: boolean = false;
    isNidDisabled: boolean = false;
    isauthorize: boolean = false;
}
